# Generated by Django 2.0.6 on 2020-05-13 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200513_0846'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='students',
            table='ba_student',
        ),
    ]
